#!/bin/sh

if [ "$#" -gt 1 ]; then
    echo "usage: $0 [titanic-csv-file]" >&2
    exit 1
fi

if [ "$#" -eq 1 ]; then
    f="$1"
else
    f='titanic.csv'
fi

if [ ! -f "$f" ]; then
    echo "$0: can't read $f: No such file" >&2
    exit 1
fi

# Turn "<surname>, <title> <husband's firtnames> (<original name>)"
# into <title> <husband's firtnames> <surname> (<original name>)
# Keep field Survived,Pclass,Name,Sex,Age,Embarked
sed -E -e '1d' \
    -e 's/"(.*), ([^\(]*)( \(.*\))? ?"/\2 \1\3/' \
    -e 's/""/"/g' "$f" | cut -d ',' -f '2-6,12'

